<?php
$z[0]=Array("global","",1319,1344);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("channel","\r\n				      	<li>\r\n				      		<a href='[field:typeurl/]' [field:rel/] class=\" link\"><span>[field:typename/]</span></a>\r\n				      	</li>\r\n				      	",1396,1716);
$z[1][4]['type']="top";
$z[1][4]['row']="10";
$z[1][4]['currentstyle']="<li class='hover'> <a href='~typelink~' ~rel~ class=";
$z[1][4]['link"><span>~typename~</span></a></li>"']="";

?>